version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_KEY=your-app-key
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=your-database-name
      - DB_USERNAME=your-database-username
      - DB_PASSWORD=your-database-password

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: your-database-name
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data: